services:
  # Postgres (database)
  postgres:
    image: docker.io/postgres:15
    volumes:
      - ./data/postgres:/docker-entrypoint-initdb.d # SQL files to import on build
    env_file:
      - ./env/postgres.env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER}'"]
      start_period: 5s
      interval: 5s
      timeout: 60s
    restart: always

  # Keycloak (Identity Provider)
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    volumes:
      - ./data/keycloak:/opt/keycloak/data/import # Contains a preconfigured realm which will be imported
    ports:
      - 9999:8080/tcp
    env_file:
      - ./env/keycloak.env
    command:
      - start-dev
      - --import-realm # Import the dev realm
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--head", "-fsS", "http://localhost:8080/health/ready"]
      start_period: 5s
      interval: 5s
      timeout: 240s
    restart: always

  # Atlas
  atlas:
    image: safe-sky.io/atlas:edge
    pull_policy: always
    volumes:
      - ./data/atlas:/etc/atlas # Contains the license and aerodrome data
    ports:
      - 8080:3842/tcp # Web UI
      - 3842:3842/tcp # REST API
    env_file:
      - ./env/postgres.env
      - ./env/atlas.env
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    command:
      - --serve-statics
    healthcheck:
      test: ["CMD", "/bin/atlascmd", "system", "health"]
      start_period: 5s
      interval: 5s
      timeout: 30s
    restart: unless-stopped
